const baseImagesPath = '../../assets/'

export default {
  upnextLogo: require(baseImagesPath + 'logo.png'),
  upnextWhiteLogo: require(baseImagesPath + 'white_logo.png'),
  upnextNewLogo: require(baseImagesPath + 'green_logo.png'),

  banner: require(baseImagesPath + 'feed/banner.png'),
  discover: require(baseImagesPath + 'feed/discover.png'),
  startProject: require(baseImagesPath + 'feed/start_a_project.png'),
  startProjectFull: require(baseImagesPath + 'start_a_project_full.png'),
  playStats: require(baseImagesPath + 'startup_deck/play.png'),
  viewStats: require(baseImagesPath + 'startup_deck/eye.png'),
  coinsStats: require(baseImagesPath + 'startup_deck/coins.png'),
  theProblem: require(baseImagesPath + 'startup_deck/problem.png'),
  solution: require(baseImagesPath + 'startup_deck/solution.png'),
  uniq: require(baseImagesPath + 'startup_deck/uniq.png'),
  cross: require(baseImagesPath + 'cross.png'),

  photoButton: require(baseImagesPath + 'startup/camera_button.png'),
  placeholderStartupImage: require(baseImagesPath + 'startup/placeholder_startup.png'),

  menu_notifications: require(baseImagesPath + 'menu/notifications.png'),
  menu_startup: require(baseImagesPath + 'menu/startup.png'),
  menu_launchpad: require(baseImagesPath + 'menu/launchpad.png'),
  menu_feed: require(baseImagesPath + 'menu/feed.png'),

  space1: require(baseImagesPath + 'my_profile/space_1.png'),
  space2: require(baseImagesPath + 'my_profile/space_2.png'),
  space3: require(baseImagesPath + 'my_profile/space_3.png'),
  space4: require(baseImagesPath + 'my_profile/space_4.png'),

  uploadPlus: require(baseImagesPath + 'my_profile/upload_plus.png'),
  uploadWhitePlus: require(baseImagesPath + 'my_profile/upload_white_plus.png'),
  uploadEdit: require(baseImagesPath + 'my_profile/upload_edit.png'),
  uploadWhiteEdit: require(baseImagesPath + 'my_profile/upload_white_edit.png'),
 editProfile: require(baseImagesPath + 'edit-profile.png'),
  uploadImage: require(baseImagesPath + 'upload_image.png'),
  userNoPhoto: require(baseImagesPath + 'my_profile/user_no_photo.png'),
  male: require(baseImagesPath + 'my_profile/male.png'),
  female: require(baseImagesPath + 'my_profile/female.png'),
  nonbinary: require(baseImagesPath + 'my_profile/nonbinary.png'),
  coin_background: require(baseImagesPath + 'my_profile/coin_background.png'),

  complete: require(baseImagesPath + 'status/complete.png'),
  notComplete: require(baseImagesPath + 'status/not_complete.png'),

  candidateIcon: require(baseImagesPath + 'network/candidate.png'),
  searcherIcon: require(baseImagesPath + 'network/searcher.png'),
  candidateDisabledIcon: require(baseImagesPath + 'network/candidate_disabled.png'),
  searcherDisabledIcon: require(baseImagesPath + 'network/searcher_disabled.png'),
  webIcon: require(baseImagesPath + 'network/web.png'),
  tiktokIcon: require(baseImagesPath + 'network/tiktok.png'),
  facebookIcon: require(baseImagesPath + 'network/facebook.png'),
  youtubeIcon: require(baseImagesPath + 'network/youtube.png'),

  search: require(baseImagesPath + 'search.png'),
  newSearch: require(baseImagesPath + 'search2.png'),
  filter:require(baseImagesPath + 'network/filters.png'),
  clearSearch: require(baseImagesPath + 'search-clear.png'),
  inputSearch: require(baseImagesPath + 'input_search.png'),
  chat: require(baseImagesPath + 'white_chat.png'),
  arrowBottom: require(baseImagesPath + 'arrow_bottom.png'),
  check: require(baseImagesPath + 'check.png'),
  upnext: require(baseImagesPath + 'upnext.png'),
  stats: require(baseImagesPath + 'stats.png'),
  edit: require(baseImagesPath + 'edit.png'),
  editCard: require(baseImagesPath + 'edit_button_card.png'),
  trashIcon: require(baseImagesPath + 'trash.png'),
  upload: require(baseImagesPath + 'upload.png'),
  chatPerson: require(baseImagesPath + 'chat.png'),
  merge: require(baseImagesPath + 'merge.png'),
  videoCamera: require(baseImagesPath + 'video_camera.png'),
  gallery: require(baseImagesPath + 'gallery.png'),
  close: require(baseImagesPath + 'close.png'),
  plusButton: require(baseImagesPath + 'plus_button.png'),
  videoGallery: require(baseImagesPath + 'video-gallery.png'),

  view: require(baseImagesPath + 'view.png'),
  emptyShare: require(baseImagesPath + 'empty_share.png'),
  whiteShare: require(baseImagesPath + 'feed/share.png'),
  newEmptyShare: require(baseImagesPath + 'share.png'),
  comments: require(baseImagesPath + 'feed/comments.png'),

  share: require(baseImagesPath + 'startup/share.png'),
  questionMark: require(baseImagesPath + 'startup/question_mark.png'),
  doneMark: require(baseImagesPath + 'startup/done.png'),
  closeCamera: require(baseImagesPath + 'startup/close.png'),
  switchCamera: require(baseImagesPath + 'startup/switch.png'),

  camera: require(baseImagesPath + 'camera.png'),

  play: require(baseImagesPath + 'play.png'),
  pause: require(baseImagesPath + 'pause.png'),
  playWhite: require(baseImagesPath + 'play_white.png'),

  coin: require(baseImagesPath + 'coin.png'),
  upCoin: require(baseImagesPath + 'up_coin.png'),
  nftCoin: require(baseImagesPath + 'nft-icon.png'),
  emptyCoin: require(baseImagesPath + 'empty_coin.png'),
  backArrow: require(baseImagesPath + 'back_arrow.png'),
  backArrowTeam: require(baseImagesPath + 'back_arrow_team.png'),
  whiteBack: require(baseImagesPath + 'white_arrow.png'),
  

  closeCircle: require(baseImagesPath + 'close_circle.png'),
  done: require(baseImagesPath + 'done.png'),
  filters: require(baseImagesPath + 'filters.png'),

  googleLogo: require(baseImagesPath + 'google_logo.png'),
  appleLogo: require(baseImagesPath + 'apple_logo.png'),
  snapchatLogo: require(baseImagesPath + 'snapchat_logo.png'),

  flag: require(baseImagesPath + 'report/flag.png'),
  mark: require(baseImagesPath + 'report/mark.png'),
  tnxEmoji: require(baseImagesPath + 'report/tnx_emoji.png'),
  report: require(baseImagesPath + 'report/report.png'),
  favorite: require(baseImagesPath + 'report/favorite.png'),
  favoriteRemove: require(baseImagesPath + 'report/favorite_remove.png'),
  thanks: require(baseImagesPath + 'report/thanks.png'),

  shareMore: require(baseImagesPath + 'share/more.png'),
  shareCopy: require(baseImagesPath + 'share/copy.png'),
  shareWhatsap: require(baseImagesPath + 'share/whatsap.png'),
  shareInstagram: require(baseImagesPath + 'share/instagram.png'),
  shareSnapchat: require(baseImagesPath + 'share/snapchat.png'),
  shareGmail: require(baseImagesPath + 'share/gmail.png'),

  launchVideo: require(baseImagesPath + 'videos/launch.mp4'),

  loaderBanner: require(baseImagesPath + 'loader-banner.png'),

  headerLogo: require(baseImagesPath + 'header/logo.png'),
  headerWallet: require(baseImagesPath + 'header/wallet.png'),
  headerChat: require(baseImagesPath + 'header/chat.png'),

  attach: require(baseImagesPath + 'chat/attach.png'),
  record: require(baseImagesPath + 'chat/record.png'),
  isRecord: require(baseImagesPath + 'chat/is_record.png'),
  backArrowBlue: require(baseImagesPath + 'back_arrow_blue.png'),
  sendIcon: require(baseImagesPath + 'chat/send_icon_v2.png'),
  video: require(baseImagesPath + 'video.png'),
  videos: require(baseImagesPath + 'videos.png'),
  message: require(baseImagesPath + 'message.png'),
  mainShare: require(baseImagesPath + 'main_share.png'),

  startVideo: require(baseImagesPath + 'start-video.png'),
  addButton: require(baseImagesPath + 'add-button.png'),
  addVideo: require(baseImagesPath + 'add-video.png'),
  deleteTrash: require(baseImagesPath + 'delete_trash.png'),
  customMarker: require(baseImagesPath + 'custom_marker.png'),

  exampleAvatar1: require(baseImagesPath + 'network/av1.png'),
  exampleAvatar2: require(baseImagesPath + 'network/av2.png'),
}
